### ISSUE TITLE
Img url provided in seed.rb is not correct

### ISSUE THREAD

**Issue by MarikoJanes** [learn-co-curriculum/phase-4-debugging-network-requests-lab#3]
### Canvas Link

https://learning.flatironschool.com/courses/5181/assignments/180794?module_item_id=398812

### Concern

The link: http://umich.edu/~chemh215/W11HTML/SSG5/ssg5.2/FRex.png for the assignment does not work. 

### Suggested Changes

Use this link https://static.wikia.nocookie.net/pixar/images/a/a8/Rex_%28Toy_Story%29.png/revision/latest/scale-to-width-down/377?cb=20210221010941

**Comment by lizbur10** [comment]
Hi @MarikoJanes ! Thanks for bringing this to our attention. The url appears to be working now - I'm guessing it was a temporary issue on the source website. I'm going to go ahead and close this issue, but please feel free to reopen it if you're still encountering the problem.

Thanks for contributing to the Flatiron School curriculum 💙
